vich_uploader:
    db_driver: orm
    mappings:
        recette_image:
            uri_prefix: /img/recette
            upload_destination: '%kernel.project_dir%/public/img/recette'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
