vich_uploader:
  db_driver: orm

  mappings:
    profil_image:
      uri_prefix:         /assets/img/profil
      upload_destination: '%kernel.project_dir%/public/assets/img/profil'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    recette_image:
      uri_prefix:         /assets/img/recette
      upload_destination: '%kernel.project_dir%/public/assets/img/recette'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
